/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aly0nHtnfno
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import MapComponent from "./GoogleMap";
import Image from "next/image";
import { Header } from "./Header";

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-[#f0f4f8]">
      <Header />
      <main className="flex-1 container mx-auto">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    TC Colorado Classic
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Join us for a day of golf and fundraising to support our
                    local community. All proceeds will go directly to the XYZ
                    Charity.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Register Now
                  </Link>
                </div>
              </div>
              <Image
                src="/arrowhead_fairway.jpg"
                width={550}
                height={310}
                alt="Golf Course"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section
          id="event-details"
          className="w-full py-12 md:py-24 lg:py-32 bg-muted"
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Event Details
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Join us on Saturday, June 10th at the Oakwood Golf Club for a
                  day of golf, networking, and fundraising. The tournament will
                  begin at 8 AM with a shotgun start, followed by a luncheon and
                  awards ceremony.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Date</h3>
                      <p className="text-muted-foreground">
                        Saturday, June 10th, 2023
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Location</h3>
                      <p className="text-muted-foreground">
                        Oakwood Golf Club
                        <br />
                        123 Golf Course Rd, Anytown USA
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Schedule</h3>
                      <p className="text-muted-foreground">
                        8 AM - Shotgun Start
                        <br />
                        12 PM - Luncheon and Awards
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
              <MapComponent address="Arrowhead Golf Course" />
            </div>
          </div>
        </section>
        <section id="charity-info" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                  About the Charity
                </h2>
                <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  The XYZ Charity is a non-profit organization dedicated to
                  supporting our local community. All proceeds from the Charity
                  Golf Tournament will go directly to funding their programs and
                  initiatives.
                </p>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Learn More
                </Link>
              </div>
              <Image
                src="/tc.jpeg"
                width={550}
                height={310}
                alt="TC"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section
          id="sponsorship"
          className="w-full py-12 md:py-24 lg:py-32 bg-muted"
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Our Sponsors
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  We're so thankful for for our sponsors!
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-1 lg:gap-12">
              <div className="grid grid-cols-2 gap-4 mx-auto">
                <img
                  src="/placeholder.svg"
                  width="150"
                  height="150"
                  alt="Sponsor Logo 1"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-contain"
                />
                <img
                  src="/placeholder.svg"
                  width="150"
                  height="150"
                  alt="Sponsor Logo 2"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-contain"
                />
                <img
                  src="/placeholder.svg"
                  width="150"
                  height="150"
                  alt="Sponsor Logo 3"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-contain"
                />
                <img
                  src="/placeholder.svg"
                  width="150"
                  height="150"
                  alt="Sponsor Logo 4"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-contain"
                />
              </div>
            </div>
          </div>
        </section>
        <section
          id="registration"
          className="w-full pb-12 md:pb-24 lg:pb-32 bg-muted"
        >
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Register for the Tournament
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Sign up today to secure your spot in the inagural TC Colorado
                Classic. Spots are limited, so don't wait!
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex flex-col gap-2">
                <Input type="text" placeholder="Name" className="max-w-lg" />
                <Input type="email" placeholder="Email" className="max-w-lg" />
                <Input type="tel" placeholder="Phone" className="max-w-lg" />
                <Button type="submit">Register Now</Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">
          &copy; 2024 TC Coloradoo Classic
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Contact Us
          </Link>
        </nav>
      </footer>
    </div>
  );
}
